-- TEMPLATE - Adjust tablespace names, location and sizing
--
-- create-tbs.sql - Create BIS 6.7 Tablespace on Oracle DB
--
-- Revision: 2020-05-22
--
-- Copyright 2010-2023 SEEBURGER AG, Germany. All rights reserved.

-- You need to be connected to a non-CDB or correct PDB
-- PDBSEEBIS is the sample name for a plugable database
-- ALTER SESSION SET CONTAINER="PDBSEEBIS";

-- You need to run this as DBA
SET ROLE "DBA";


CREATE BIGFILE TABLESPACE SEEDTA DATAFILE SIZE 2G
    AUTOEXTEND ON NEXT 128M MAXSIZE UNLIMITED
    LOGGING EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE BIGFILE TABLESPACE SEEIDX DATAFILE SIZE 2G
    AUTOEXTEND ON NEXT 128M MAXSIZE UNLIMITED
    LOGGING EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE BIGFILE TABLESPACE SEELOB DATAFILE SIZE 5G
    AUTOEXTEND ON NEXT 1024M MAXSIZE UNLIMITED
    LOGGING EXTENT MANAGEMENT LOCAL -- UNIFORM SIZE 64M
    SEGMENT SPACE MANAGEMENT AUTO;

-- end of SQL script
